version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0-stretch
    working_directory: ~/project
    environment:
    steps: &default_steps
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Node Dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Test
          command: DEBUG=* npm test
  centos:
    docker:
      - image: circleci/node:10.11.0-stretch
    working_directory: ~/project
    environment:
    steps:
      <<: *default_steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
